WITH SRC_S AS ( SELECT * FROM {{ source('Raw_core_banking', 'BRANCHES') }} ),
SRC_A AS ( SELECT * FROM {{ source('control', 'REF_SOURCE_SYSTEM') }} ),

LOGIC_S AS (
    SELECT 
        NULLIF(TRIM(CAST(BRANCH_CODE AS VARCHAR)), '') AS BRANCH_BK,
        BRANCH_NAME,
        CITY,
        CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS LOAD_DTS
    FROM SRC_S
),
LOGIC_A AS ( SELECT * FROM SRC_A ),

RENAME_S AS (
    SELECT BRANCH_BK, BRANCH_NAME, CITY, LOAD_DTS FROM LOGIC_S
),
RENAME_A AS (
    SELECT TABLE_NAME, REC_SRC, BKCC FROM LOGIC_A
),

FILTER_S AS (
    SELECT * FROM RENAME_S WHERE BRANCH_BK IS NOT NULL
),
FILTER_A AS (
    SELECT * FROM RENAME_A WHERE TABLE_NAME = 'BRANCHES'
),

JOIN_RESULTS AS (
    SELECT 
        s.*, 
        a.REC_SRC, 
        a.BKCC
    FROM FILTER_S s
    INNER JOIN FILTER_A a ON '1' = '1'
),

FINAL AS (
    SELECT 
        *,
        MD5_BINARY(UPPER(CONCAT_WS('||',
            COALESCE(NULLIF(TRIM(CAST(BKCC AS VARCHAR)), ''), '^^'),
            COALESCE(NULLIF(TRIM(CAST(BRANCH_BK AS VARCHAR)), ''), '^^')
        ))) AS BRANCH_HK,
        MD5_BINARY(UPPER(NULLIF(CONCAT(
            IFNULL(TRIM(BRANCH_NAME::text), '^^'), '||',
            IFNULL(TRIM(CITY::text), '^^')
        ), '^^||^^'))) AS HASHDIFF
    FROM JOIN_RESULTS
)
SELECT * FROM FINAL
