WITH SRC AS (
    SELECT * FROM {{ source('core_banking', 'CREDIT_CARD_APPLICATION') }}
),
LOGIC AS (
    SELECT
        NULLIF(TRIM(CAST(CARD_ACCOUNT_ID AS VARCHAR)), '') AS CARD_ACCOUNT_ID,
        NULLIF(TRIM(CAST(CREDIT_LIMIT AS VARCHAR)), '') AS CREDIT_LIMIT,
        NULLIF(TRIM(CAST(CARD_TYPE AS VARCHAR)), '') AS CARD_TYPE,
        NULLIF(TRIM(CAST(CREDIT_SCORE AS VARCHAR)), '') AS CREDIT_SCORE,
        NULLIF(TRIM(CAST(APPROVAL_STATUS AS VARCHAR)), '') AS APPROVAL_STATUS,
        NULLIF(TRIM(CAST(ANNUAL_FEE AS VARCHAR)), '') AS ANNUAL_FEE
    FROM SRC
),
RENAME AS (
    SELECT CARD_ACCOUNT_ID, CREDIT_LIMIT, CARD_TYPE, CREDIT_SCORE, APPROVAL_STATUS, ANNUAL_FEE
    FROM LOGIC
),
FILTER AS (
    SELECT * FROM RENAME
    WHERE CARD_ACCOUNT_ID IS NOT NULL
),
JOIN_LAYER AS (
    SELECT
        f.CARD_ACCOUNT_ID,
        f.CREDIT_LIMIT,
        f.CARD_TYPE,
        f.CREDIT_SCORE,
        f.APPROVAL_STATUS,
        f.ANNUAL_FEE,
        rss.REC_SRC,
        rss.BKCC
    FROM FILTER f
    INNER JOIN {{ source('control', 'REF_SOURCE_SYSTEM') }} rss
        ON UPPER(rss.SOURCE_SYSTEM_CODE) = UPPER('CORE_BANKING')
    WHERE rss.ACTIVE_FLAG = TRUE
),
FINAL AS (
    SELECT
        CARD_ACCOUNT_ID,
        CREDIT_LIMIT,
        CARD_TYPE,
        CREDIT_SCORE,
        APPROVAL_STATUS,
        ANNUAL_FEE,
        MD5_BINARY(UPPER(CONCAT_WS('||',
            COALESCE(NULLIF(TRIM(CAST(CARD_ACCOUNT_ID AS VARCHAR)), ''), '^^'),
            COALESCE(NULLIF(TRIM(CAST(BKCC AS VARCHAR)), ''), '^^')
        ))) AS CREDIT_CARD_HK,
        CARD_ACCOUNT_ID AS CREDIT_CARD_BK,
        MD5_BINARY(UPPER(NULLIF(CONCAT_WS('||',
            IFNULL(TRIM(CREDIT_LIMIT::VARCHAR), '^^'),
            IFNULL(TRIM(CARD_TYPE::VARCHAR), '^^'),
            IFNULL(TRIM(CREDIT_SCORE::VARCHAR), '^^'),
            IFNULL(TRIM(APPROVAL_STATUS::VARCHAR), '^^'),
            IFNULL(TRIM(ANNUAL_FEE::VARCHAR), '^^')
        ), '^^'))) AS HASHDIFF,
        current_timestamp() AS LOAD_DTS,
        REC_SRC,
        BKCC
    FROM JOIN_LAYER
)
SELECT * FROM FINAL
