WITH SRC AS (
    SELECT * FROM {{ source('card_processor', 'CUSTOMERS') }}
),
LOGIC AS (
    SELECT
        NULLIF(TRIM(CAST(CP_CUSTOMER_CODE AS VARCHAR)), '') AS CP_CUSTOMER_CODE,
        NULLIF(TRIM(CAST(CP_EMAIL AS VARCHAR)), '') AS CP_EMAIL
    FROM SRC
),
RENAME AS (
    SELECT
        CP_CUSTOMER_CODE AS CUSTOMER_BK_SRC,
        CP_EMAIL AS CUSTOMER_EMAIL
    FROM LOGIC
),
FILTER AS (
    SELECT * FROM RENAME
    WHERE CUSTOMER_EMAIL IS NOT NULL
      AND CUSTOMER_BK_SRC IS NOT NULL
),
JOIN_LAYER AS (
    SELECT
        f.CUSTOMER_BK_SRC,
        f.CUSTOMER_EMAIL,
        rss.REC_SRC,
        rss.BKCC
    FROM FILTER f
    INNER JOIN {{ source('control', 'REF_SOURCE_SYSTEM') }} rss
        ON UPPER(rss.SOURCE_SYSTEM_CODE) = UPPER('CARD_PROCESSOR')
    WHERE rss.ACTIVE_FLAG = TRUE
),
FINAL AS (
    SELECT
        CUSTOMER_EMAIL,
        CUSTOMER_BK_SRC AS CUSTOMER_BK,
        MD5_BINARY(UPPER(CONCAT_WS('||',
            COALESCE(NULLIF(TRIM(CAST(CUSTOMER_EMAIL AS VARCHAR)), ''), '^^'),
            COALESCE(NULLIF(TRIM(CAST(BKCC AS VARCHAR)), ''), '^^')
        ))) AS CUSTOMER_HK,
        current_timestamp() AS LOAD_DTS,
        REC_SRC,
        BKCC
    FROM JOIN_LAYER
)
SELECT * FROM FINAL