{{ config(materialized='view') }}

WITH
SRC AS (
    SELECT
        TXN_ID,
        ACCOUNT_NO,
        TXN_TYPE,
        AMOUNT,
        TXN_TIMESTAMP,
        BALANCE_AFTER
    FROM {{ source('raw_core_banking', 'transactions') }}
),
LOGIC AS (
    SELECT
        TXN_ID,
        ACCOUNT_NO,
        TXN_TYPE,
        AMOUNT,
        TXN_TIMESTAMP,
        BALANCE_AFTER
    FROM SRC
),
RENAME AS (
    SELECT
        TXN_ID AS TRANSACTION_BK,
        ACCOUNT_NO AS ACCOUNT_BK,
        TXN_TYPE AS TXN_TYPE,
        AMOUNT AS AMOUNT,
        TXN_TIMESTAMP AS TXN_TIMESTAMP,
        BALANCE_AFTER AS BALANCE_AFTER
    FROM LOGIC
),
FILTER AS (
    SELECT
        *
    FROM RENAME
    WHERE TRANSACTION_BK IS NOT NULL
),
JOIN AS (
    SELECT
        *
    FROM FILTER
),
FINAL AS (
    SELECT
        MD5_BINARY(CONCAT_WS('||', TRANSACTION_BK)) AS TRANSACTION_HK,
        MD5_BINARY(CONCAT_WS('||', ACCOUNT_BK)) AS ACCOUNT_HK,
        MD5_BINARY(CONCAT_WS('||', TRANSACTION_BK, ACCOUNT_BK)) AS LNK_ACCOUNT_TRANSACTION_HK,
        MD5_BINARY(CONCAT_WS('||', TXN_TYPE, AMOUNT, TXN_TIMESTAMP, BALANCE_AFTER)) AS HASHDIFF_SAT_TRANSACTION,
        TRANSACTION_BK,
        ACCOUNT_BK,
        TXN_TYPE,
        AMOUNT,
        TXN_TIMESTAMP,
        BALANCE_AFTER,
        CURRENT_TIMESTAMP() AS LOAD_DTS,
        'RAW_CORE_BANKING.TRANSACTIONS' AS REC_SRC
    FROM JOIN
)
SELECT * FROM FINAL
